### ISSUE TITLE
Error: "Request textDocument/documentSymbol failed"

### ISSUE THREAD

**Issue by Majkel1999** [latex-lsp/texlab-vscode#822]
When working with a `*.tex` document, in uncertain circumstances, the error `Request textDocument/documentSymbol failed` shows up. 
I am still looking into the root cause, but as of yet I was not able to properly reproduce the above error. 

```
[Error - 9:56:14 AM] Request textDocument/documentSymbol failed.
Error: name must not be falsy
	at t.validate (c:\Users\<Redacted>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:25900)
	at new t (c:\Users\<Redacted>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:26195)
	at V (c:\Users\<Redacted>\.vscode\extensions\efoerster.texlab-5.4.0-win32-x64\dist\extension.js:1:213015)
	at c (c:\Users\<Redacted>\.vscode\extensions\efoerster.texlab-5.4.0-win32-x64\dist\extension.js:1:251012)
	at t.map (c:\Users\<Redacted>\.vscode\extensions\efoerster.texlab-5.4.0-win32-x64\dist\extension.js:1:251098)
	at Object.asDocumentSymbols (c:\Users\<Redacted>\.vscode\extensions\efoerster.texlab-5.4.0-win32-x64\dist\extension.js:1:220833)
	at i (c:\Users\<Redacted>\.vscode\extensions\efoerster.texlab-5.4.0-win32-x64\dist\extension.js:1:159487)
	at async n.provideDocumentSymbols (c:\Users\<Redacted>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:32515)
```

TexLab custom settings:
```
    "texlab.build.executable": "tectonic",
    "texlab.build.args": [
      "-X",
      "compile",
      "%f",
      "-Z=shell-escape",
      "--synctex",
      "--keep-logs",
      "--keep-intermediates"
    ],
    "texlab.formatterLineLength": 120,
```

Operating System:
```
Edition	Windows 10 Education
Version	21H2
OS build	19044.2486
Experience	Windows Feature Experience Pack 120.2212.4190.0
```

_I will update the issue if I can find the root cause or an example that reproduces the above error._

**Comment by Majkel1999** [comment]
The same error happens each time you add a new section, without a title. To reproduce:

1. Open a valid .tex file - it can be the main file, or a part of a bigger project.
2. Write `\section{}` 
3. The error shows up

Due to how VSCode autocompletes the second bracket in `{}` the error shows up each time you start writing.
